/**
 * GENERATED by cicd/codegen/generate-bot-politburo-client.mjs — do not edit.
 * Source template: cicd/codegen/bot-politburo-client.ts
 *
 * Typed Politburo HTTP client (openapi-fetch). New bot integrations should use this
 * instead of hand-written fetch in apiService.ts.
 */

import createClient from "openapi-fetch";
import type { paths, components } from "./politburo-api";
import { PolitburoApiError } from "../helpers/PolitburoApiError";
import { unwrapApiData } from "../helpers/apiEnvelope";
import type { MetaInfo } from "../types/DiscordInteraction";
import { getPolitburoApiKey, getPolitburoApiUrl } from "../helpers/utils";

export type CreateUserRequest = components["schemas"]["CreateUserRequest"];
export type CreateUserData = components["schemas"]["CreateUserData"];
export type CreateServerRequest = components["schemas"]["CreateServerRequest"];
export type CreateServerData = components["schemas"]["CreateServerData"];

export type PolitburoClient = {
    createUser(meta: MetaInfo, body: CreateUserRequest): Promise<CreateUserData>;
    createServer(meta: MetaInfo, body: CreateServerRequest): Promise<CreateServerData>;
};

function normalizeBaseUrl(baseUrl: string): string {
    const trimmed = baseUrl.trim();
    if (!trimmed) {
        throw new Error("Politburo API base URL is empty; set API_URL");
    }
    return new URL(trimmed).origin;
}

export function createPolitburoClient(
    baseUrl: string,
    fetchFn: typeof globalThis.fetch = globalThis.fetch,
): PolitburoClient {
    const client = createClient<paths>({
        baseUrl: normalizeBaseUrl(baseUrl),
        fetch: fetchFn,
    });

    return {
        async createUser(meta: MetaInfo, body: CreateUserRequest): Promise<CreateUserData> {
            const { data, error, response } = await client.POST("/api/v1/users", {
                params: {
                    header: {
                        "X-Discord-User-Id": meta.userId,
                        "X-Discord-Server-Id": meta.discordId,
                    },
                },
                body,
                headers: {
                    "X-API-Key": getPolitburoApiKey(),
                    "Content-Type": "application/json",
                },
            });

            if (!response.ok) {
                throw PolitburoApiError.fromBody(response.status, error ?? data);
            }

            const unwrapped = unwrapApiData<CreateUserData>(
                data as Record<string, unknown> | undefined,
            );
            if (!unwrapped) {
                throw new Error("No data received in API response");
            }
            return unwrapped;
        },

        async createServer(meta: MetaInfo, body: CreateServerRequest): Promise<CreateServerData> {
            const { data, error, response } = await client.POST("/api/v1/servers", {
                params: {
                    header: {
                        "X-Discord-User-Id": meta.userId,
                        "X-Discord-Server-Id": meta.discordId,
                    },
                },
                body,
                headers: {
                    "X-API-Key": getPolitburoApiKey(),
                    "Content-Type": "application/json",
                },
            });

            if (!response.ok) {
                throw PolitburoApiError.fromBody(response.status, error ?? data);
            }

            const unwrapped = unwrapApiData<CreateServerData>(
                data as Record<string, unknown> | undefined,
            );
            if (!unwrapped) {
                throw new Error("No data received in API response");
            }
            return unwrapped;
        },
    };
}

let cachedClient: PolitburoClient | null = null;
let cachedClientBaseUrl: string | null = null;

export function getPolitburoClient(baseUrl?: string): PolitburoClient {
    const url = (baseUrl ?? getPolitburoApiUrl()).trim();
    if (!cachedClient || cachedClientBaseUrl !== url) {
        cachedClientBaseUrl = url;
        cachedClient = createPolitburoClient(url);
    }
    return cachedClient;
}
