apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - data
  - observability
  - apps

images:
  - name: politburo
    newName: ghcr.io/sanketpandia/politburo
    newTag: main
  - name: comrade-bot
    newName: ghcr.io/sanketpandia/comrade-bot
    newTag: main
