apiVersion: v1
kind: Service
metadata:
  name: comrade-bot
  namespace: ie-apps
  labels:
    app: comrade-bot
spec:
  ports:
    - port: 9091
      targetPort: metrics
      name: metrics
  selector:
    app: comrade-bot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comrade-bot
  namespace: ie-apps
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: comrade-bot
  template:
    metadata:
      labels:
        app: comrade-bot
    spec:
      imagePullSecrets:
        - name: ghcr-cred
      containers:
        - name: comrade-bot
          image: comrade-bot:main
          envFrom:
            - secretRef:
                name: comrade-bot-env
          ports:
            - containerPort: 9091
              name: metrics
          readinessProbe:
            httpGet:
              path: /healthz
              port: metrics
            initialDelaySeconds: 15
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            initialDelaySeconds: 30
            periodSeconds: 30
