apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: ie-observability
  labels:
    app: cadvisor
spec:
  ports:
    - port: 8080
      name: http
      targetPort: http
  selector:
    app: cadvisor
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cadvisor
  namespace: ie-observability
spec:
  selector:
    matchLabels:
      app: cadvisor
  template:
    metadata:
      labels:
        app: cadvisor
    spec:
      automountServiceAccountToken: false
      priorityClassName: system-node-critical
      tolerations:
        - operator: Exists
          effect: NoSchedule
      containers:
        - name: cadvisor
          image: gcr.io/cadvisor/cadvisor:v0.49.1
          ports:
            - containerPort: 8080
              name: http
          args:
            - --housekeeping_interval=10s
            - --max_housekeeping_interval=15s
            - --docker_only=false
            - --store_container_labels=false
            - --whitelisted_container_labels=io.kubernetes.container.name,io.kubernetes.pod.name,io.kubernetes.pod.namespace,io.kubernetes.pod.uid
          securityContext:
            privileged: true
          volumeMounts:
            - name: rootfs
              mountPath: /rootfs
              readOnly: true
            - name: var-run
              mountPath: /var/run
              readOnly: true
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: disk
              mountPath: /dev/disk
              readOnly: true
            - name: k3s-containerd
              mountPath: /run/k3s/containerd
              readOnly: true
      volumes:
        - name: rootfs
          hostPath:
            path: /
        - name: var-run
          hostPath:
            path: /var/run
        - name: sys
          hostPath:
            path: /sys
        - name: disk
          hostPath:
            path: /dev/disk
        - name: k3s-containerd
          hostPath:
            path: /run/k3s/containerd
