apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: ie-observability
  labels:
    app: grafana
spec:
  ports:
    - port: 3000
      name: http
  selector:
    app: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: ie-observability
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: docker.io/grafana/grafana:latest
          ports:
            - containerPort: 3000
              hostIP: 127.0.0.1
              hostPort: 3000
              name: http
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-credentials
                  key: GRAFANA_ADMIN_PASSWORD
            - name: GF_SERVER_ROOT_URL
              value: https://monitor.comradebot.cc
            - name: GF_SERVER_DOMAIN
              value: monitor.comradebot.cc
            - name: GF_SECURITY_COOKIE_SECURE
              value: "true"
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
            - name: GF_LOG_LEVEL
              value: warn
            - name: GF_ANALYTICS_REPORTING_ENABLED
              value: "false"
            - name: GF_PATHS_PROVISIONING
              value: /etc/grafana/provisioning
            - name: GF_INSTALL_PLUGINS
              value: grafana-worldmap-panel
          volumeMounts:
            - name: data
              mountPath: /var/lib/grafana
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboards
              mountPath: /etc/grafana/provisioning/dashboards
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: grafana-data
        - name: datasources
          configMap:
            name: grafana-datasources
        - name: dashboards
          configMap:
            name: grafana-dashboards
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: ie-observability
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
