name: Politburo CI

on:
  pull_request:
    paths:
      - 'services/politburo/**'
      - 'openapi/**'
      - 'cicd/**'
      - 'Makefile'
  push:
    branches: [main]
    paths:
      - 'services/politburo/**'
      - 'openapi/**'
      - 'cicd/**'
      - 'Makefile'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v4
      - name: Generate, test, and build
        run: docker build --file services/politburo/Dockerfile.dev --target ci --tag politburo-ci:${{ github.sha }} .

  production-image:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out source
        uses: actions/checkout@v4
      - name: Build production image
        run: docker build --file services/politburo/Dockerfile --tag politburo:${{ github.sha }} .
